/**
 * Field definitions for the generic collection editor.
 *
 * These mirror the whitelists in backend/controllers/admin_controller.py.
 * A field listed here but not whitelisted there is simply ignored on save,
 * which is the safe direction for the mistake to go.
 *
 * type: text | textarea | rich | number | money | toggle | select | color
 *       | image | json | list | benefits
 */

export const SCHEMAS = {
  products: {
    title: 'Products',
    sub: 'Every tin on the shop. Adding one here puts it on the storefront immediately.',
    singular: 'product',
    columns: [
      { key: 'name', label: 'Name', primary: true, sub: 'slug' },
      { key: 'botanical_name', label: 'Botanical', muted: true },
      { key: 'accent_color', label: 'Colour', type: 'swatch' },
      { key: 'is_featured', label: 'Featured', type: 'bool' },
      { key: 'is_active', label: 'Live', type: 'bool' },
      { key: 'sort_order', label: 'Order', type: 'num' },
    ],
    fields: [
      { key: 'name', label: 'Name', type: 'text', required: true, hint: 'e.g. Butterfly Pea' },
      { key: 'slug', label: 'Web address', type: 'text', prefix: '/product/',
        hint: 'Leave blank to build it from the name. Changing it breaks old links.' },
      { key: 'botanical_name', label: 'Botanical name', type: 'text', hint: 'e.g. Clitoria ternatea' },
      { key: 'script_word', label: 'Script line', type: 'text',
        hint: 'The handwritten line on the packaging, e.g. "Herbal Tea".' },
      { key: 'tagline', label: 'Tagline', type: 'text', hint: "e.g. Nature's blue elixir" },
      { key: 'short_desc', label: 'Short description', type: 'textarea',
        hint: 'One or two sentences. Used on cards and in search results.' },
      { key: 'description', label: 'Description', type: 'rich' },
      { key: 'story', label: 'The longer story', type: 'rich',
        hint: 'Sourcing, tradition, why it is made this way. This is what AI search quotes.' },
      { key: 'accent_color', label: 'Accent colour', type: 'color',
        hint: 'The brewed colour. Drives the page theme for this tea.' },
      { key: 'accent_soft', label: 'Lighter accent', type: 'color' },
      { key: 'hero_image', label: 'Main image', type: 'image' },
      { key: 'benefits', label: 'Benefits', type: 'benefits',
        hint: 'Shown on the product page. Traditional uses, not medical claims.' },
      { key: 'ingredients', label: 'Ingredients', type: 'list' },
      { key: 'badges', label: 'Badges', type: 'list', hint: 'e.g. Caffeine free, 100% natural' },
      { key: 'brewing', label: 'Brewing', type: 'json',
        hint: '{"temp_c": 90, "minutes": 4, "steps": ["…"]}' },
      { key: 'seo', label: 'SEO', type: 'json',
        hint: '{"title": "…", "description": "…", "keywords": ["…"]}' },
      { key: 'is_caffeine_free', label: 'Caffeine free', type: 'toggle' },
      { key: 'is_featured', label: 'Show on the homepage', type: 'toggle' },
      { key: 'is_active', label: 'Live on the shop', type: 'toggle' },
      { key: 'sort_order', label: 'Sort order', type: 'number' },
    ],
    defaults: { is_active: true, is_caffeine_free: true, sort_order: 99, accent_color: '#8F7222' },
  },

  product_variants: {
    title: 'Pack sizes',
    sub: 'Prices and stock live here, one row per SKU.',
    singular: 'pack size',
    columns: [
      { key: 'sku', label: 'SKU', primary: true },
      { key: 'label', label: 'Size' },
      { key: 'price', label: 'Price', type: 'money' },
      { key: 'stock', label: 'Stock', type: 'num' },
      { key: 'is_active', label: 'Live', type: 'bool' },
    ],
    fields: [
      { key: 'product_id', label: 'Product', type: 'ref', ref: 'products', required: true },
      { key: 'sku', label: 'SKU', type: 'text', required: true, hint: 'Unique. e.g. ZH-BP-100' },
      { key: 'label', label: 'Size label', type: 'text', required: true, hint: 'e.g. 100 g' },
      { key: 'weight_grams', label: 'Weight in grams', type: 'number' },
      { key: 'price', label: 'Price', type: 'money', required: true },
      { key: 'compare_at_price', label: 'Was price', type: 'money',
        hint: 'Shown struck through. Leave blank for no discount.' },
      { key: 'stock', label: 'Stock on hand', type: 'number' },
      { key: 'low_stock_at', label: 'Warn me below', type: 'number' },
      { key: 'is_default', label: 'Default size', type: 'toggle',
        hint: 'The size selected first. Only one per product.' },
      { key: 'is_active', label: 'Available to buy', type: 'toggle' },
      { key: 'sort_order', label: 'Sort order', type: 'number' },
    ],
    defaults: { is_active: true, stock: 0, low_stock_at: 5, sort_order: 1 },
  },

  categories: {
    title: 'Categories',
    sub: 'How the shop page groups products.',
    singular: 'category',
    columns: [
      { key: 'name', label: 'Name', primary: true, sub: 'slug' },
      { key: 'sort_order', label: 'Order', type: 'num' },
      { key: 'is_active', label: 'Live', type: 'bool' },
    ],
    fields: [
      { key: 'name', label: 'Name', type: 'text', required: true },
      { key: 'slug', label: 'Web address', type: 'text' },
      { key: 'description', label: 'Description', type: 'textarea' },
      { key: 'image_url', label: 'Image', type: 'image' },
      { key: 'sort_order', label: 'Sort order', type: 'number' },
      { key: 'is_active', label: 'Live', type: 'toggle' },
    ],
    defaults: { is_active: true, sort_order: 1 },
  },

  faqs: {
    title: 'Questions',
    sub: 'Shown on the site and published as structured data, which is what AI search and Google read.',
    singular: 'question',
    columns: [
      { key: 'question', label: 'Question', primary: true },
      { key: 'category', label: 'Topic', muted: true },
      { key: 'sort_order', label: 'Order', type: 'num' },
      { key: 'is_active', label: 'Live', type: 'bool' },
    ],
    fields: [
      { key: 'question', label: 'Question', type: 'text', required: true,
        hint: 'Write it the way a customer would type it into search.' },
      { key: 'answer', label: 'Answer', type: 'rich', required: true,
        hint: 'Answer directly in the first sentence. That sentence is what gets quoted.' },
      { key: 'category', label: 'Topic', type: 'select',
        options: ['general', 'product', 'ingredients', 'shipping', 'ordering', 'referral', 'safety'] },
      { key: 'scope', label: 'Where it shows', type: 'text', hint: '"global", or "product:<slug>"' },
      { key: 'sort_order', label: 'Sort order', type: 'number' },
      { key: 'is_active', label: 'Live', type: 'toggle' },
    ],
    defaults: { is_active: true, category: 'general', scope: 'global', sort_order: 50 },
  },

  coupons: {
    title: 'Coupons',
    sub: 'Discount codes. These stack with referral discounts unless you set a minimum that prevents it.',
    singular: 'coupon',
    columns: [
      { key: 'code', label: 'Code', primary: true, sub: 'description' },
      { key: 'value', label: 'Value', type: 'num' },
      { key: 'used_count', label: 'Used', type: 'num' },
      { key: 'is_active', label: 'Live', type: 'bool' },
    ],
    fields: [
      { key: 'code', label: 'Code', type: 'text', required: true, hint: 'What the customer types. Not case sensitive.' },
      { key: 'description', label: 'What it is for', type: 'text' },
      { key: 'discount_type', label: 'Type', type: 'select', options: ['percent', 'fixed'], required: true },
      { key: 'value', label: 'Value', type: 'number', required: true,
        hint: 'A percentage, or an amount in rupees, depending on the type.' },
      { key: 'min_order', label: 'Minimum order', type: 'money' },
      { key: 'max_discount', label: 'Maximum discount', type: 'money', hint: 'Caps a percentage coupon.' },
      { key: 'usage_limit', label: 'Total uses allowed', type: 'number', hint: 'Blank for unlimited.' },
      { key: 'per_user_limit', label: 'Uses per customer', type: 'number' },
      { key: 'starts_at', label: 'Starts', type: 'datetime' },
      { key: 'ends_at', label: 'Ends', type: 'datetime' },
      { key: 'is_active', label: 'Live', type: 'toggle' },
    ],
    defaults: { is_active: true, discount_type: 'percent', per_user_limit: 1, min_order: 0 },
  },

  pages: {
    title: 'Pages',
    sub: 'Standalone pages: policies, guides, journal entries.',
    singular: 'page',
    columns: [
      { key: 'title', label: 'Title', primary: true, sub: 'slug' },
      { key: 'page_type', label: 'Type', muted: true },
      { key: 'is_published', label: 'Live', type: 'bool' },
    ],
    fields: [
      { key: 'title', label: 'Title', type: 'text', required: true },
      { key: 'slug', label: 'Web address', type: 'text', prefix: '/p/' },
      { key: 'excerpt', label: 'Summary', type: 'textarea' },
      { key: 'body', label: 'Content', type: 'rich', hint: 'Markdown is supported.' },
      { key: 'hero_image', label: 'Header image', type: 'image' },
      { key: 'page_type', label: 'Type', type: 'select', options: ['page', 'legal', 'guide', 'journal'] },
      { key: 'seo', label: 'SEO', type: 'json' },
      { key: 'author', label: 'Author', type: 'text' },
      { key: 'read_minutes', label: 'Reading time', type: 'number' },
      { key: 'is_published', label: 'Published', type: 'toggle' },
    ],
    defaults: { is_published: true, page_type: 'page' },
  },

  nav_items: {
    title: 'Menus',
    sub: 'The links in the header and footer.',
    singular: 'link',
    columns: [
      { key: 'label', label: 'Label', primary: true, sub: 'href' },
      { key: 'menu', label: 'Menu', muted: true },
      { key: 'sort_order', label: 'Order', type: 'num' },
      { key: 'is_active', label: 'Live', type: 'bool' },
    ],
    fields: [
      { key: 'label', label: 'Label', type: 'text', required: true },
      { key: 'href', label: 'Links to', type: 'text', required: true, hint: 'e.g. /shop' },
      { key: 'menu', label: 'Which menu', type: 'select', required: true,
        options: ['header', 'footer_shop', 'footer_learn', 'footer_company', 'legal', 'mobile'] },
      { key: 'badge', label: 'Badge', type: 'text', hint: 'Small label, e.g. "New".' },
      { key: 'is_external', label: 'Opens a different site', type: 'toggle' },
      { key: 'sort_order', label: 'Sort order', type: 'number' },
      { key: 'is_active', label: 'Show it', type: 'toggle' },
    ],
    defaults: { is_active: true, menu: 'header', sort_order: 10 },
  },

  testimonials: {
    title: 'Testimonials',
    sub: 'Customer quotes used across the site.',
    singular: 'testimonial',
    columns: [
      { key: 'author', label: 'Who', primary: true, sub: 'city' },
      { key: 'rating', label: 'Rating', type: 'num' },
      { key: 'is_active', label: 'Live', type: 'bool' },
    ],
    fields: [
      { key: 'author', label: 'Name', type: 'text', required: true },
      { key: 'role', label: 'Description', type: 'text', hint: 'e.g. Verified buyer' },
      { key: 'city', label: 'City', type: 'text' },
      { key: 'quote', label: 'What they said', type: 'textarea', required: true },
      { key: 'rating', label: 'Stars', type: 'number' },
      { key: 'avatar_url', label: 'Photo', type: 'image' },
      { key: 'is_active', label: 'Live', type: 'toggle' },
      { key: 'sort_order', label: 'Sort order', type: 'number' },
    ],
    defaults: { is_active: true, rating: 5, sort_order: 10 },
  },

  reviews: {
    title: 'Reviews',
    sub: 'Customer reviews. Nothing appears on the site until you approve it.',
    singular: 'review',
    columns: [
      { key: 'author_name', label: 'Who', primary: true, sub: 'title' },
      { key: 'rating', label: 'Rating', type: 'num' },
      { key: 'is_approved', label: 'Approved', type: 'bool' },
    ],
    fields: [
      { key: 'author_name', label: 'Name', type: 'text' },
      { key: 'rating', label: 'Stars', type: 'number' },
      { key: 'title', label: 'Headline', type: 'text' },
      { key: 'body', label: 'Review', type: 'textarea' },
      { key: 'is_approved', label: 'Show on the site', type: 'toggle' },
      { key: 'is_verified', label: 'Verified buyer', type: 'toggle' },
    ],
    defaults: {},
  },

  locations: {
    title: 'Locations',
    sub: 'Used for local search results and the contact details on the site.',
    singular: 'location',
    columns: [
      { key: 'name', label: 'Name', primary: true, sub: 'city' },
      { key: 'kind', label: 'Type', muted: true },
      { key: 'is_active', label: 'Live', type: 'bool' },
    ],
    fields: [
      { key: 'name', label: 'Name', type: 'text', required: true },
      { key: 'kind', label: 'Type', type: 'select', options: ['hq', 'store', 'pickup', 'service_area'] },
      { key: 'line1', label: 'Address line 1', type: 'text' },
      { key: 'line2', label: 'Address line 2', type: 'text' },
      { key: 'city', label: 'City', type: 'text', required: true },
      { key: 'state', label: 'State', type: 'text', required: true },
      { key: 'pincode', label: 'Pincode', type: 'text' },
      { key: 'phone', label: 'Phone', type: 'text' },
      { key: 'whatsapp', label: 'WhatsApp', type: 'text', hint: 'Digits with country code, no +.' },
      { key: 'email', label: 'Email', type: 'text' },
      { key: 'latitude', label: 'Latitude', type: 'number' },
      { key: 'longitude', label: 'Longitude', type: 'number' },
      { key: 'service_areas', label: 'Areas served', type: 'list' },
      { key: 'opening_hours', label: 'Opening hours', type: 'json' },
      { key: 'is_primary', label: 'Main location', type: 'toggle' },
      { key: 'is_active', label: 'Live', type: 'toggle' },
    ],
    defaults: { is_active: true, kind: 'hq', country: 'India' },
  },

  page_sections: {
    title: 'Homepage sections',
    sub: 'Reorder, retitle or hide the blocks that make up each page.',
    singular: 'section',
    columns: [
      { key: 'title', label: 'Title', primary: true, sub: 'section_key' },
      { key: 'page', label: 'Page', muted: true },
      { key: 'sort_order', label: 'Order', type: 'num' },
      { key: 'is_active', label: 'Shown', type: 'bool' },
    ],
    fields: [
      { key: 'page', label: 'Page', type: 'text', required: true },
      { key: 'section_key', label: 'Key', type: 'text', required: true },
      { key: 'component', label: 'Block type', type: 'text', required: true },
      { key: 'eyebrow', label: 'Eyebrow', type: 'text' },
      { key: 'title', label: 'Heading', type: 'text' },
      { key: 'subtitle', label: 'Subheading', type: 'text' },
      { key: 'body', label: 'Body', type: 'rich' },
      { key: 'items', label: 'Items', type: 'json' },
      { key: 'cta', label: 'Button', type: 'json', hint: '{"label": "Shop", "href": "/shop"}' },
      { key: 'sort_order', label: 'Sort order', type: 'number' },
      { key: 'is_active', label: 'Shown', type: 'toggle' },
    ],
    defaults: { page: 'home', is_active: true, sort_order: 10 },
  },

  redirects: {
    title: 'Redirects',
    sub: 'Point old addresses at new ones so links and search rankings survive a rename.',
    singular: 'redirect',
    columns: [
      { key: 'from_path', label: 'From', primary: true, sub: 'to_path' },
      { key: 'hits', label: 'Hits', type: 'num' },
      { key: 'is_active', label: 'Live', type: 'bool' },
    ],
    fields: [
      { key: 'from_path', label: 'Old address', type: 'text', required: true },
      { key: 'to_path', label: 'New address', type: 'text', required: true },
      { key: 'status_code', label: 'Type', type: 'select', options: [301, 302] },
      { key: 'is_active', label: 'Live', type: 'toggle' },
    ],
    defaults: { is_active: true, status_code: 301 },
  },
}

export const CONTENT_TABS = ['faqs', 'pages', 'nav_items', 'testimonials', 'reviews', 'page_sections', 'locations', 'redirects']
